# Generated by Django 2.0.3 on 2019-10-01 10:35

import datetime
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Collection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(default='', max_length=50, verbose_name='微信ID')),
                ('collect_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='收藏时间')),
            ],
            options={
                'verbose_name': '收藏',
                'verbose_name_plural': '收藏',
            },
        ),
        migrations.CreateModel(
            name='Follower',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('followed', models.CharField(default='', max_length=200, verbose_name='被关注者')),
                ('follower', models.CharField(default='', max_length=200, verbose_name='关注者')),
                ('follow_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='关注时间')),
            ],
            options={
                'verbose_name': '关注',
                'verbose_name_plural': '关注',
            },
        ),
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=15, verbose_name='标题')),
                ('content', models.TextField(default='')),
                ('is_secret', models.IntegerField(default=0, verbose_name='是否开放')),
                ('summary', models.CharField(default='', max_length=200, verbose_name='摘要')),
                ('read_times', models.IntegerField(default=0, verbose_name='阅读数')),
                ('star_times', models.IntegerField(default=0, verbose_name='点赞数')),
                ('collect_times', models.IntegerField(default=0, verbose_name='收藏数')),
                ('hot', models.IntegerField(verbose_name='热度')),
                ('create_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '笔记',
                'verbose_name_plural': '笔记',
            },
        ),
        migrations.CreateModel(
            name='Recommend',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.CharField(max_length=500, verbose_name='图片链接')),
                ('url', models.CharField(max_length=500, verbose_name='链接')),
                ('create_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '推荐',
                'verbose_name_plural': '推荐',
            },
        ),
        migrations.CreateModel(
            name='Star',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(default='', max_length=50, verbose_name='微信ID')),
                ('star_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='点赞时间')),
                ('note', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Main.Note', verbose_name='笔记id')),
            ],
            options={
                'verbose_name': '点赞',
                'verbose_name_plural': '点赞',
            },
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=100, unique=True, verbose_name='类别名称')),
                ('count', models.IntegerField(verbose_name='该类别笔记数量')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('openId', models.CharField(default='', max_length=200, unique=True, verbose_name='用户微信唯一ID')),
                ('avatarUrl', models.URLField(default='', max_length=500, verbose_name='用户微信头像')),
                ('country', models.CharField(default='', max_length=100, verbose_name='用户微信国家')),
                ('user_bh', models.CharField(default=uuid.UUID('6fa459ea-ee8a-3ca4-894e-db77e160355e'), max_length=50, unique=True, verbose_name='用户唯一ID')),
                ('province', models.CharField(default='', max_length=100, verbose_name='用户微信城市')),
                ('city', models.CharField(default='', max_length=100, verbose_name='用户微信区域')),
                ('language', models.CharField(default='', max_length=100, verbose_name='用户微信语言')),
                ('background', models.ImageField(blank=True, default='/default/default.jpg', null=True, upload_to='UserProFilebg/%Y/%m/6fa459ea-ee8a-3ca4-894e-db77e160355e', verbose_name='背景图')),
                ('nickName', models.CharField(max_length=20, verbose_name='微信用户名')),
                ('name', models.CharField(max_length=20, verbose_name='用户名')),
                ('birthday', models.DateField(default=datetime.datetime.now, verbose_name='出生日期')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='UserProFilebg/avatar/%y/%d/6fa459ea-ee8a-3ca4-894e-db77e160355e')),
                ('mobile', models.CharField(blank=True, max_length=11, null=True, verbose_name='手机号')),
                ('gender', models.CharField(choices=[('2', '女'), ('1', '男')], default='1', max_length=10, verbose_name='性别')),
                ('thesignature', models.TextField(default='', max_length=200, verbose_name='用户签名')),
                ('agreement', models.BooleanField(default=False, verbose_name='是否阅读协议')),
                ('email', models.EmailField(blank=True, max_length=100, null=True, verbose_name='邮箱')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='注册时间')),
            ],
            options={
                'verbose_name': '用户',
                'verbose_name_plural': '用户',
            },
        ),
        migrations.CreateModel(
            name='User_Note',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(default='', max_length=200, verbose_name='微信ID')),
                ('note', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Main.Note', verbose_name='笔记id')),
            ],
        ),
        migrations.AddField(
            model_name='note',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Main.Subject', verbose_name='类别'),
        ),
        migrations.AddField(
            model_name='collection',
            name='note',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Main.Note', verbose_name='笔记id'),
        ),
    ]
