# Generated by Django 2.0.3 on 2019-10-01 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='hot',
            field=models.IntegerField(default=0, verbose_name='热度'),
        ),
        migrations.AlterField(
            model_name='note',
            name='title',
            field=models.CharField(default='', max_length=100, verbose_name='标题'),
        ),
    ]
