# Generated by Django 2.0.3 on 2019-10-02 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0002_auto_20191001_1946'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='avatar',
        ),
        migrations.RemoveField(
            model_name='user',
            name='background',
        ),
        migrations.AddField(
            model_name='subject',
            name='is_internal',
            field=models.BooleanField(default=False, verbose_name='是否为内置'),
        ),
        migrations.AlterField(
            model_name='subject',
            name='count',
            field=models.IntegerField(default=0, verbose_name='该类别笔记数量'),
        ),
        migrations.AlterField(
            model_name='user',
            name='gender',
            field=models.CharField(choices=[('1', '男'), ('2', '女')], default='1', max_length=10, verbose_name='性别'),
        ),
    ]
